[phases.setup]
nixPkgs = ["php83", "php83Extensions.pdo_pgsql", "composer"]

[phases.install]
cmds = ["composer install --no-interaction --optimize-autoloader --no-dev"]

[start]
cmd = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=8080"
